
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE teams (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  owner_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  hexxa_1_id INTEGER NOT NULL,
  hexxa_2_id INTEGER NOT NULL,
  hexxa_3_id INTEGER NOT NULL,
  battles INTEGER DEFAULT 0,
  battles_won INTEGER DEFAULT 0,
  battles_lost INTEGER DEFAULT 0,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (owner_id) REFERENCES user (id),
  FOREIGN KEY (hexxa_1_id) REFERENCES hexxas (id),
  FOREIGN KEY (hexxa_2_id) REFERENCES hexxas (id),
  FOREIGN KEY (hexxa_3_id) REFERENCES hexxas (id)
);

CREATE TABLE hexxas (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  element_id TEXT NOT NULL,
  resistance TEXT NOT NULL,
  attacks TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
